### ISSUE TITLE
thread question

### ISSUE THREAD

**Issue by baymin0220** [Tw1ddle/geometrize-lib-example#4]
First of all thanks for your work and for this great library!  I find that thread doesn't work properly. As the number of threads increases, the time consuming becomes longer. (-s 1 -t rotated_ellipse -c 100 -m 10) 0.02s(maxthreads=1) 0.07s(maxthreads=2) 0.297074s(maxthreads=4)  . And my *pro file is 
"""
include(lib/geometrize/geometrize/geometrize.pri)

CONFIG -= qt
CONFIG += warn_on console c++11

TARGET = geometrize_lib_example

HEADERS += lib/args/args.hxx \
           lib/stb/stb_image.h \
           lib/stb/stb_image_write.h

SOURCES += main.cpp
"""
Thanks for you help!!!

**Comment by Tw1ddle** [comment]
Hi, each thread generates shapes and then the "best fitting" shape produced from all the threads is chosen, so increasing the thread count increases the accuracy of the shapes that are chosen rather than increasing the speed.

Hope that makes sense, the code for it is here: https://github.com/Tw1ddle/geometrize-lib/blob/abb12e93174ebc211e4b15e15d130579ebf7cd97/geometrize/geometrize/model.cpp#L85

**Comment by baymin0220** [comment]
Are these threads parallel? I find that the speed drops too much as the number of threads increases. In addition, Do you have any suggestions for speeding up? Thanks!

**Comment by Tw1ddle** [comment]
Yes they do run in parallel.

You could make it run faster if you use smaller images, or reduce the number of candidate shapes and/or mutations per shape: https://github.com/Tw1ddle/geometrize-lib-example#options
